apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: historymanager
  labels:
    team: aura
spec:
  image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
  port: 8080
  {{- if .Values.onprem }}
  webproxy: true
  {{- end }}
  filesFrom:
    - secret: historymanager
      mountPath: /var/run/secrets/gcp/
  env:
    - name: PROJECT_ID
      value: {{ .Values.bigQuery.projectID }}
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/run/secrets/gcp/sa.json
