name: Build and push charts
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/chart.yaml'

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: 'gh-historymanager@nais-io.iam.gserviceaccount.com'
          token_format: 'access_token'
      - uses: docker/login-action@v2
        with:
          registry: europe-north1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: helm package charts
      - run: helm push historymanager*.tgz oci://europe-north1-docker.pkg.dev/nais-io/nais
