name: Build and deploy
on:
  push:
    branches:
      - main

jobs:
  build-push:
    name: Build and push image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.image }}
    steps:
      - uses: actions/checkout@v2
      - run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY}:$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
      - run: docker build -t $IMAGE .
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker push $IMAGE
      - name: Set IMAGE as output
        id: image
        run: echo ::set-output name=image::${IMAGE}

  deploy:
    name: Deploy to Kubernetes
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.NAIS_APP_PRIVATE_KEY }}
          app-id: ${{ secrets.NAIS_APP_ID }}
          repo: navikt/nais-yaml
      - name: Checkout nais-yaml
        uses: actions/checkout@v2
        with:
          repository: navikt/nais-yaml
          token: ${{ steps.get-token.outputs.token }}
          path: nais-yaml
      - name: Bump version in nais-yaml
        run: |
          export version=${{needs.build-push.outputs.image}}
          cd nais-yaml
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          sed -E -i "s#image: ghcr.io/${GITHUB_REPOSITORY}:.+#image: ${version}#" vars/global.yaml
          git add .
          git --no-pager diff --cached
          git commit -a -m "Bump ${version}"
          git push
